### ISSUE TITLE
Hide "Reinstall" button when installed version is newer

### ISSUE THREAD

**Issue by Nairou** [GrapheneOS/Apps#116]
Example: Google Play Store updates itself to a newer version that that listed in the app. Because of this, it is listed with a "Reinstall" button, as if an update was available, when in fact the version installed is newer and should not be reinstalled.

Alternative options:

- Remove or disable the button, to show that no action is needed.
- Show an "Open" button, as with other installed apps, but show an icon next to it (i.e. exclamation).

In either case, opening app details can show that a newer version installed than what the app offers, without giving the impression up-front that the app should be reinstalled.

**Comment by thestinger** [comment]
Note we're fixing this UX issue from Play Store:

https://github.com/GrapheneOS/platform_frameworks_base/commit/f1bf13ff9e399aea9ba6c897c91f0b00b46bf8fc

**Comment by empratyush** [comment]
[done](https://github.com/GrapheneOS/Apps/commit/992068ae73785c847e55ef83c2ac43b9e9fab19e)
