### ISSUE TITLE
Add ability to hide GSF apps in App store app

### ISSUE THREAD

**Issue by snrkl** [GrapheneOS/Apps#124]
It would be useful to be able to hide GSF components so that I don't inadvertantly install them in my main profile. 

This would be a large convenience for me and improve usability of the app store app. 

I also have kids with GrapheneOS devices and it would be useful to be able to do this on their devices as they aren't yet able to fully understand why we don't have it loaded in their main profile.

**Comment by quh4gko8** [comment]
This can be potentially handled by giving an option to make the filters persistent or not across app session

**Comment by thestinger** [comment]
The UI has been greatly improved. I don't see a good reason to add a toggle for this.
