### ISSUE TITLE
Update status notification frequency

### ISSUE THREAD

**Issue by chrinz** [GrapheneOS/Apps#127]
Apps creates notification "Apps are already fully up-to-date" frequently, without respect to the 'check for updates' frequency specified in the app (approx every 2-3 hours).  Assume app is also checking for updates at this frequency.

**Comment by whats-a-diorama** [comment]
I'm also experiencing this, and one thing that I've noticed is that it often occurs after waking/unlocking my phone. So if I clear the notification, lock my phone, let it sit for 5-10 minutes, and then unlock it, I'll often get the notification again.

It happens a lot, but admittedly, sometimes it _doesn't_ happen. Unfortunately I haven't found a way to reproduce it perfectly 100% of the time. But when it does happen, it can be as much as several times an hour.

I'm not sure if it's actually checking for updates each time, but I suspect that it might be, as there's a momentary delay between when I unlock my phone and when the notification appears.

If it helps, I have the "Check for updates periodically" option turned on and the "Auto update installed apps" option turned off. "Auto download app updates interval" is set to 6 hours and "Permitted network" is set to "Any".

**Comment by whats-a-diorama** [comment]
This issue appears to be resolved for me with the release of version 6.

Thank you very much to all.
