### ISSUE TITLE
Installing Play Services after uninstall from Play Store version gives "Installation Failed" / "The app is corrupt" message with multi user setup

### ISSUE THREAD

**Issue by danwdart** [GrapheneOS/Apps#168]
Just came across this after the latest Play Services update delivered by Play Store.

Reproduce by:

Have multiple users
Update Play services with Play Store
Uninstall Play services with Apps
Install Play Services with Apps

Result: "The app is corrupt" message

I think the reason might be that Play Services is only uninstalled in current user profile.

Workaround: Uninstall Play Services in all profiles.

Suggested fix: Uninstall should either suggest uninstalling in all profiles or install should detect profiles' installed Play Services, maybe?

Thanks

**Comment by ccxex29** [comment]
Had this problem as well. The workaround worked great. Thanks!

**Comment by thestinger** [comment]
Should no longer be an issue in practice since the Play Store updates are limited to not actually upgrading the version.

It's still an issue on legacy 3rd gen but if you accept the updates there, it will break badly until you downgrade anyway.
