### ISSUE TITLE
Add friendly app icon to metadata JSON format and implement in app

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/Apps#20]

**Comment by empratyush** [comment]
[done](https://github.com/GrapheneOS/apps.grapheneos.org/commit/4e0e43a1c99403ece1939517354a4c744246c305)

**Comment by octocorvus** [comment]
Is this for adding icons for apps. So, that we can show it in the 'Apps' app UI?

**Comment by empratyush** [comment]
> Is this for adding icons for apps. So, that we can show it in the 'Apps' app UI?

yes.

**Comment by octocorvus** [comment]
Do the icons exist on the server?

**Comment by empratyush** [comment]
[not yet](https://github.com/GrapheneOS/apps.grapheneos.org/blob/main/generate.py)
