### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/Apps#21]

**Comment by oumno** [comment]
Made a design for search bar and the search in general. [See designs.](https://www.figma.com/file/C2jlidwrJTiYwBcTzfpM4e/GrapheneOS---Apps?node-id=23%3A2228) - Figma link.

Page 11. A: Search field. B: Search mode. C: Search results view. D: No results returned.

Future work could be to incorporate filters and sorting to this view. But for now this may do.

**Comment by empratyush** [comment]
[done](https://github.com/GrapheneOS/Apps/pull/118)
