### ISSUE TITLE
apps are not auto updating on Pixel 6 running with GOS

### ISSUE THREAD

**Issue by hjangadi** [GrapheneOS/Apps#234]
I am using GOS on Pixel 6 running with GMS as sandboxed apps. However my apps are not autoupdating. Any solution please?

**Comment by thestinger** [comment]
Play Store updates apps in the background automatically. It works fine on GrapheneOS. It prefers only doing updates when the device is not being used and has been idle for a while. It will often delay them for a long time if the device is in active use. Not specific to GrapheneOS in any way

**Comment by thestinger** [comment]
There's nothing special about the releases of Google Play in our app repository and this repository is for our app repository client software so this is the wrong place to file this.
