### ISSUE TITLE
Add support for major Android version streams

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/Apps#25]
Apps such as GSF have distinct versions for each major Android version. Support multiple streams (e.g Android 12 and Android 13) to make sure apps like GSF get properly updated.

**Comment by empratyush** [comment]
[do](https://github.com/GrapheneOS/apps.grapheneos.org/commit/6eddc867befbe0d74c8b8b27592ccb6c2d372a53)[ne.](https://github.com/GrapheneOS/Apps/blob/6c8badc7a2a4d6cc8ee3b12e4ae05ef6177f3945/app/src/main/java/org/grapheneos/apps/client/utils/network/MetaDataHelper.kt#L181-L192)
