### ISSUE TITLE
Play services app corrupt

### ISSUE THREAD

**Issue by ar-** [GrapheneOS/Apps#259]
I have exactly the same problem as in #122 . It seems to be an ongoing error and appears to be unresolved until today. I was not able to reopen it so here it goes again:

Been trying to get Google Play Services installed but the download reaches ~40% of the 105mb file, the download bar skips to 100% and attempts to install the package. Failure message is: "app is corrupt, cannot be installed." Have tried reinstalling Apps apk, uninstalling Play Store and Google Services Framework to no avail.

#122 was closed with a stupid comment "the error message is correct" and with a description of why the error occurs. 

I see at least 3 errors remaining here:

Error 1: 

The error message is obviously wrong. I think the message should be changed to something like "the app can't be installed because you have already installed a different version of it". 

Or perhaps the stupid comment in #122 is wrong. 

Nevertheless, the app pretends to do a download and then pretends to cancel it at 40%. Then it tries to do install the corrupted download and tell you that the file is corrupt. That makes sense because trying to install a corrupted download will never work and should cause exactly that error. 

And then they would still be the question why do you pretend to do a download and give a false error message, while the actual error is something totally different ?

Error 2: 

Installing play Play services still does not work. I have 3 accounts with Google and I have 3 more accounts without Google. Graphene encourages the intense use of profiles. 

Now I want to create another account with Google and it simply does not work. So I have to use a sloppy workaround using one of my existing accounts. 

This workaround is a data privacy risk and is not coherent with the goals of the graphene project.

Is it possible to fix this error or to describe a way how I can fix it on my phone? I have a rather complex set up on my phone and it is the primary phone for my daily use sofa factory reset is not an option.

Error 3:

bugs and error reports are apparently simply being closed off without actually fixing them. Just like it happened in #122 . 

closing a bug report with a false and stupid comment and forwarding the user to Matrix is not a very professional way to deal with bugs in a software project.

**Comment by thestinger** [comment]
Apps version 8 is available in the alpha channel. It already provides improved error reporting and a better UI for almost everything including downloads.

**Comment by thestinger** [comment]
@ar- There's no bug and this works the same on GrapheneOS as every other Android OS. You can't install an older version of an app than you already have in another profile in a new one. You also can't install an app with the same app id as one you already have installed but which has an incompatible signing key. This is how it's intended to work due to the installed APKs being shared between each profile where the same app is installed. That's how Android works to save bandwidth and storage. It's secure due to signature verification and downgrade protection, but if you try to install incompatible variants of an app you'll get errors.

**Comment by thestinger** [comment]
Please use https://discuss.grapheneos.org/ or the Matrix chat room for support requests. This isn't a bug report. Please don't make attacks on the people giving you support because you aren't happy with how things work in Android.
