### ISSUE TITLE
Google Play services can not be installed - application corrupt

### ISSUE THREAD

**Issue by ar-** [GrapheneOS/Apps#260]
I just opened #259, but it has been deleted, so unfortunately I cannot comment on it anymore. Nevertheless the issue is remaining. It would be kind not to delete GitHub issues, so I can still comment on them even if they are closed.

#259 was closed with the comment:

There's no bug and this works the same on GrapheneOS as every other Android OS. You can't install an older version of an app than you already have in another profile in a new one. You also can't install an app with the same app id as one you already have installed but which has an incompatible signing key. This is how it's intended to work due to the installed APKs being shared between each profile where the same app is installed. That's how Android works to save bandwidth and storage. It's secure due to signature verification and downgrade protection, but if you try to install incompatible variants of an app you'll get errors.

(I only know that because I received an email with that comment. I can't see it because it was deleted)

There are 3 issues with this response:

1: I know all that and I agree to it. I also understand the error description in #122 .
2: in #259 I described 3 errors and I enumerated them explicitly. The comment above only addresses "error 1", but "error 2" and "error 3" remain unresolved.
3: I honestly and sincerely don't know what to do now so I'm kindly responding to the comment above. 

Here is what I am NOT trying to do:

1. I don't want to install an older version of an app in a different profile.

2. I don't want to install an app with a different signing key.

3. I don't want to do anything insecure, I don't want to downgrade anything and I don't want to do anything with a different signature.

Here is what I actually DO want to do:

1: I want to create a brand new account (profile) and want to install the sandbox Google Play store on it. How can I do that ?

**Comment by thestinger** [comment]
You've been asked to use Matrix or https://discuss.grapheneos.org/ for support request.

You are trying to install an older version of the app than what you have installed elsewhere. You updated Play services via the Play Store before we were fully blocking it. You can't do that. Either downgrade it to what's in the stable channel or use the alpha channel in the new profile.

I've explained that the new app repository client version 8 is available with much better error reporting.

**Comment by thestinger** [comment]
This isn't an appropriate use of the issue tracker. It's a support request, not an issue report. I've given you support regardless, and despite you being rude and attacking us. I won't be giving more support and if you keep opening support requests after being asked not to do that, I'll have to use moderation capabilities to stop this.
