### ISSUE TITLE
An app that is disabled cannot be updated (for the benefit of other user profiles)

### ISSUE THREAD

**Issue by rustybird** [GrapheneOS/Apps#266]
If an app is disabled in the user profile where Apps is running, it will not be updated.

But consider e.g. the use case of having the always running Owner profile with disabled Play apps automatically apply global updates - so that when you occasionally unlock a secondary user profile with Play apps *enabled*, they will already be up-to-date. (Currently, the secondary user profile would start with outdated versions. Updating them might then require a download of hundreds of megabytes at an inconvenient time.)

**Comment by muhomorr** [comment]
This is an OS limitation. Updating a disabled app will enable it back.

**Comment by rustybird** [comment]
Ah, that's why! Thanks for the hint.
