### ISSUE TITLE
Allow Play services to be updated without depending on Play Store

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [GrapheneOS/Apps#269]
Now that Play services and Play Store depend on each other:
1. If Play Store is installed but disabled, Play services can no longer be updated without re-enabling Play Store
2. If Play services & Play Store have updates available, choosing to only update Play services will also update Play Store

This seems like an oversight since you can have Play services on alpha channel and Play Store on stable and Play services can be updated anyways. While I understand having Play Store disabled is not the recommended way of running sandboxed Google Play, it has always worked fine for the apps and services I use that require Play. Therefore, I don't think it is necessary to have this restriction.

**Comment by thestinger** [comment]
It could be made possible to update components in the OS without enabling them. I don't really think we should do something differently about this in Apps. Play Store is genuinely a dependency of Play services and needed for it to be able to install/update dynamite modules, etc.

**Comment by thestinger** [comment]
I don't think we want to do this.

**Comment by thestinger** [comment]
Maybe @muhomorr has a different opinion. I think the best solution would be if updating apps didn't re-enable them, although it's such a low priority and I don't really think we want to maintain changes for that downstream.

However, you do really need Play Store for Play services to work properly even if you don't use it directly at all so this specific example isn't something we want to do anything extra to support.

**Comment by muhomorr** [comment]
There's a difference between having Play services and Play Store on different release channels and allowing to update Play services or Play Store independently. Even though Play services doesn't depend on a specific version of Play Store (and vice versa), they are expected to be on versions that aren't too far apart. Allowing updates of one but not the other would allow having Play services many months newer than the Play Store, and vice versa.

**Comment by jorgeluiscarrillo** [comment]
I think I need to clarify since based on @thestinger's comments I feel there was a misunderstanding that I was requesting an OS-level change.

An error check was added that blocks updates of Play services because one of it's dependencies, in this case Play Store, is disabled. Unattended updates for Play services won't work since the user now has to **manually** re-enable the Play Store to get around this restriction.

> Allowing updates of one but not the other would allow having Play services many months newer than the Play Store

I am proposing that we allow this to happen (as it did previously) and let the user be responsible for reduced/broken functionality.

Consider the "Play services for AR" situation. Users have the option to install and disable this app even though technically apps depending on it won't function "properly" (I assume that is why it tries to install itself). Like Play services for AR, the Play Store is just another regular sandboxed app on GrapheneOS. Requiring Play Store to be enabled after the user has decided to disable it makes the disabling user installed apps feature not as useful for this app which shouldn't be the case since it isn't special.

**Comment by r3g-5z** [comment]
> let the user be responsible for reduced/broken functionality.

I don't understand what's the point of doing this? It doesn't have any benefits at all other than having a half-baked installation of sandboxed Google Play which breaks *other* apps and future ones you install. Even if said "responsible users" are aware this is completely broken and unintended, said people are still going to be inclined to send bug reports asking us to fix something we can't fix because we do not develop Play services.

Sure this setup "works for you", but this is not something the general public should be able to do because not everyone is going to be aware this is a broken setup.

> Consider the "Play services for AR" situation. Users have the option to install and disable this app even though technically apps depending on it won't function "properly" (I assume that is why it tries to install itself).

This isn't the same thing because Play services for AR is not a critical component of Play services like Play Store is.
