### ISSUE TITLE
Feature Request: Disable Sensors Tile for All Profiles

### ISSUE THREAD

**Issue by rhclayto** [GrapheneOS/Apps#28]
Not sure if this is the right repository to ask this in, but:

Android developer settings makes available a tile to toggle sensors on & off. However, it's only available in the main profile & not user profiles. It would be a handy thing to have available in user profiles as well.

**Comment by flawedworld** [comment]
This is the issue tracker for the App Store, not the OS. The OS issue tracker can be found here: https://github.com/GrapheneOS/os-issue-tracker

Please refer to https://github.com/GrapheneOS/os-issue-tracker/issues/806 with regard to your issue.

**Comment by thestinger** [comment]
Developer options aren't meant for production use and this legacy sensors developer tile doesn't fit into how things work now.
