### ISSUE TITLE
Auto update of libraries

### ISSUE THREAD

**Issue by aurelpere** [GrapheneOS/Apps#282]
I got this error message without doing anything.
Im nit sure it is related to auto updates only...
Is there a grapheneos forum with technical questions like this if hère is not appropriate?

Unable to install Vanadium, Trichrome Library, Vanadium System WebView.

Details: 
INSTALL_FAILED_SESSION_INVALID: Not allowed to update system package to the same versionCode

**Comment by aurelpere** [comment]
Yes il using twi profiles...

**Comment by r3g-5z** [comment]
Pretty sure this is solved in latest Apps and GrapheneOS release.

**Comment by thestinger** [comment]
We haven't done a new Apps release yet but it will be solved by the next one so it can be closed.
