### ISSUE TITLE
"Missing dependency" error on trying to update disabled Google Play

### ISSUE THREAD

**Issue by rustybird** [GrapheneOS/Apps#296]
Now with #266 closed (thank you!) I tried out the brand new Apps alpha v18. (Before updating the Apps client, Google Services Framework was installed and up to date, and both Google Play Store and Google Play services were installed and outdated. All three components were disabled in the Owner profile.)

After launching the updated Apps client in the Owner profile client it shows an error popup:

"Missing dependency
Google Play services depends on Google Services Framework, which is disabled.
[Dismiss]"

Dismissing this error shows it again once more. (The UI is a bit confusing here because it doesn't look like two popups, it looks like one popup where Dismiss has to be pressed twice without visual feedback on the first press.) The same error is also shown once if I manually try to update either of the two outdated components. They are not updated. Clearing storage for Apps did not help.

**Comment by rustybird** [comment]
Interestingly it did not block the recent automatic updates of Camera and Auditor.

**Comment by muhomorr** [comment]
> This situation also blocked the automatic update of other apps unrelated to Google Play (Vanadium + Trichrome Library + Vanadium System WebView)

How did you determine that auto-update of Vanadium group was blocked by this issue?

**Comment by rustybird** [comment]
@muhomorr It was after muting the "Missing dependency" notification channel to get rid\* of Google Play related noise. I saw another notification, IIRC "Updates available". This caused me to open Apps, where I was able to manually update the Vanadium group. (If it happens again I'll pay closer attention to the exact notification details.)

No idea why it would block the Vanadium group but not Camera or Auditor. Maybe if something has dependencies at all (even if they're satisfiable), dependency resolution can fail if there's a dependency problem anywhere else? Assuming that it wasn't a network related fluke.

---

\* Get rid of it *as a notification*. Whenever I occasionally open Apps, there'll still be a dozen or so "Missing dependency" popups stacked on top of each other.

**Comment by muhomorr** [comment]
Vanadium auto update is not blocked by this issue.

Since version 18, app update check happens separately from app auto-update, see https://github.com/GrapheneOS/Apps/releases/tag/18

**Comment by rustybird** [comment]
This time the Vanadium auto update was successful (to v113.0.5672.62.1). I'm still puzzled about what happened last time. Anyway, sorry for the noise.

**Comment by muhomorr** [comment]
> I saw another notification, IIRC "Updates available". This caused me to open Apps, where I was able to manually update the Vanadium group. 

What I meant is that "Updates available" notification being shown doesn't mean that auto-update is broken.
Since version 18, auto-update happens only when the device is idle, but update check can happen at any time. Update check is what produces the "Updates available" notification.

**Comment by rustybird** [comment]
> auto-update happens only when the device is idle, but update check can happen at any time.

Ah, that makes sense! Thank you.

**Comment by rustybird** [comment]
In this [code block](https://github.com/GrapheneOS/Apps/blob/9bb136db0aacfbaef8c5ffe3c8980eb582087dba/app/src/main/java/app/grapheneos/apps/core/Dependenies.kt#L100-L122) where the error seems to originate, a package state's raw `osPackageInfo` is checked to see if it's enabled. Should its `status()` be checked instead? IIUC that would treat a disabled package as enabled when `canUpdateDisabledPackages` is true.

**Comment by muhomorr** [comment]
> Should its status() be checked instead?

No, fresh installation of package that depends on disabled package should fail.
