### ISSUE TITLE
App update not syncing with Google Play Store

### ISSUE THREAD

**Issue by User1966** [GrapheneOS/Apps#298]
GIVEN I have enabled 'silent' System Updates in Owner Profile
AND I have installed a new profile with Google Play and Google Play Services (Sandboxed)
WHEN see  'Apps are up-to-date' as a silent notification
AND I check the Google Play Store updates
THEN I see that App updates can be installed/and are not up to date

Expected:
The app update and google play need to sync.

Provide secure delivery method for attachments

**Comment by thestinger** [comment]
Our app repository client is an entirely separate thing from the Play Store.

**Comment by User1966** [comment]
@thestinger Sorry I'll redraft, that's not what I mean

**Comment by User1966** [comment]
Redrafted but can't reopen, so new issue
