### ISSUE TITLE
Vanadium not detected

### ISSUE THREAD

**Issue by bioluks** [GrapheneOS/Apps#302]
Hi all!
Coming from [this issue](https://github.com/Tobi823/ffupdater/issues/404), since it wasn't the right place to discuss GrapheneOS/Vanadium specific issues.
I don't have GrapheneOS installed, but am a Vanadium user. Android 13 - AOSP custom ROM. Since [it should be possible to update](https://github.com/Tobi823/ffupdater/issues/404#issuecomment-1529989822) it via GrapheneOS App Repository, I downloaded it, and the only apps I can see and install/update are: _Apps_, _Auditor_, _Camera_ and _PDF Viewer_.

Before I installed the App Repository, I had Vanadium installed. Vanadium is not getting detected. Without uninstalling 'Apps', I uninstalled and installed Vanadium again (btw I'm using the precompiled APK's on the GitLab repo for Vanadium). Nothing changed.

Since 'Apps' can also be used on other Android 12+ systems I hope I'm not in the wrong place asking for support.

**Comment by thestinger** [comment]
I checked and it only currently accepts these being installed as system packages. It's working as intended right now and it won't be possible to use it for this yet.
