### ISSUE TITLE
Feature Request - Contacts App Custom Fields, More Fields

### ISSUE THREAD

**Issue by User1966** [GrapheneOS/Apps#309]
GIVEN I have migrated from Apple
AND I open the contacts app
AND I have imported contacts
WHEN I open the app to add more information such as Birthday, Suffix, Prefix ect...
THEN I cannot

Please match Google/Apple Contact Fields list or give option to customise fields, so you can add say birthday field ect...

**Comment by thestinger** [comment]
It's not planned right now.

**Comment by User1966** [comment]
Please add it to the list as this is a high significant area, or at least indicate which 3rd party apps you recommend instead

**Comment by User1966** [comment]
@thestinger 
Please add it to the list as this is a high significant area, contact import/export and fields

Or at least indicate which 3rd party apps you recommend instead of the official one?
