### ISSUE TITLE
Feature Request - SMS Search Function

### ISSUE THREAD

**Issue by User1966** [GrapheneOS/Apps#310]
GIVEN I have opened SMS/Messenger app
WHEN I try to search for some text I remember
THEN I cannot

Expected
Provide search functionality?

**Comment by thestinger** [comment]
Improving AOSP Messaging is not planned. It will eventually be replaced with another app. Carrier-based texts should be avoided though.

**Comment by User1966** [comment]
@thestinger Ideally one wouldn't need to use SMS at all, but it still very common I read in USA/elsewhere, SMS and email the few 'open' systems that everyone can use.

You have to consider that friends/family won't just use a secure messaging system, they appear in what I read, see to stick with What's app, social media, SMS, email...

This isn't a discussion about secure messaging systems.  Unless GrapheneOS supports SIP, VOIP, native secure messaging apps as part of the Owner Profile

**Comment by thestinger** [comment]
There are other SMS apps available. We don't plan to actively develop/extend AOSP Messaging much.
