### ISSUE TITLE
BMO TD and RBC banking apps do not open

### ISSUE THREAD

**Issue by energypink** [GrapheneOS/Apps#324]
Canadian BMO TD and RBC banking apps do not open with latest Graphene update as of Oct 11, 2023.
Scotiabank opens up. Installed CIBC, I am not a client, it seems to launch ok.

**Comment by thestinger** [comment]
Did they work before?

**Comment by energypink** [comment]
yes

**Comment by energypink** [comment]
it still doesnt work with new updates, scotia, credit union apps work no issues, i tried CIBC too without the account, seems launching

**Comment by akc3n** [comment]
@energypink this Apps repository and issue tracker is for the GrapheneOS client app called Apps. The purpose of Apps is to provide end users with standalone apps developed by GrapheneOS.

More [info](https://github.com/GrapheneOS/Apps/releases/tag/20)...

For banking app reports, tracking compatibility with GrapheneOS, and workarounds, please use:
https://github.com/PrivSec-dev/banking-apps-compat-report#banking-apps-compatibility-with-grapheneos
