### ISSUE TITLE
When does it support multilingual versions?

### ISSUE THREAD

**Issue by jiangjiali** [GrapheneOS/Apps#341]
Looking forward to arranging.

**Comment by thestinger** [comment]
It's planned but isn't current a high priority. Can you clarify exactly what you want to see implemented? Do you want to have multi-language support for app names, descriptions and so on? The app also isn't currently localized in terms of the strings included it. We currently lack the resources to do these things properly.

**Comment by jiangjiali** [comment]
> It's planned but isn't current a high priority. Can you clarify exactly what you want to see implemented? Do you want to have multi-language support for app names, descriptions and so on? The app also isn't currently localized in terms of the strings included it. We currently lack the resources to do these things properly.

I am a Chinese user and simply want to see the meaning of Chinese. This is more intuitive.
However, I have already translated it myself.

https://github.com/jiangjiali/GrapheneOS-Apps

**Comment by jiangjiali** [comment]
Introduce more resources from it. I want to build a resource server myself, but I don't know the overall structure of this resource package.

**Comment by jiangjiali** [comment]
The entire system is safe and concise to use. Very suitable for living alone in everything.
