### ISSUE TITLE
Notification overhaul + solve Notification spam bug

### ISSUE THREAD

**Issue by Zanthed** [GrapheneOS/Apps#69]
This is a current blocker for official release.

**Comment by Zanthed** [comment]
Notifications need to have proper priorities and separate channels for different things.

Already updated should be minimum priority.

**Comment by empratyush** [comment]
[do](https://github.com/GrapheneOS/Apps/commit/b44d0a463d8ed2343ad10393076343f2d3cda4da)[ne.](https://github.com/GrapheneOS/Apps/commit/9ad97a5532e0624de4082baadf81d9e01dd8bb95)
