### ISSUE TITLE
Add categories/tags to apps to sort them and split them up into tabs

### ISSUE THREAD

**Issue by Zanthed** [GrapheneOS/Apps#71]
Need to be able to sort (tags/categories), split up into groups/tabs, and determine whether an app is an official mirror (e.g. Play services), one of our apps (Auditor, Camera, PDFViewer, etc), or a rebuild/repackage of a 3rd-party app.

**Comment by empratyush** [comment]
[done](https://github.com/GrapheneOS/Apps/pull/118)
