### ISSUE TITLE
Repositories

### ISSUE THREAD

**Issue by trymeouteh** [GrapheneOS/Apps#78]
Please add the ability to host your own repository and be able to add/remove repositories in the settings. Similar to F-Droid and other Linux distros like Debian and Ubuntu.

**Comment by thestinger** [comment]
Each repository can make their own builds using their repository URL and public key. Having one client obtaining apps from multiple repositories goes against Android's app source security model. It would prevent treating our first party repository as a known and trusted source of apps in the OS by default. It would prevent having device managers whitelist it as a source of apps. It would weaken the security model. It's one of many reasons we aren't using F-Droid.

**Comment by rusty-snake** [comment]
> Each repository can make their own builds using their repository URL and public key.

Does anybody know is this already happened (for some useful app collection)?
