### ISSUE TITLE
Suggestion regarding 'Apps' icon

### ISSUE THREAD

**Issue by dhishkyaon** [GrapheneOS/Apps#83]
the current 'Apps'  app icon is nice but it will look much better if it has thin border lines compared to the current one. I am suggesting this because Auditor app has very thin border lines compared to 'Apps' app and it looks like they are from different devs/community.

**Comment by thestinger** [comment]
I think we're going to leave it as is for now.

**Comment by dhishkyaon** [comment]
![Picsart_22-02-15_10-27-45-444.jpg](https://user-images.githubusercontent.com/88529066/153995801-e126cf74-6299-4766-8eae-42f9af32e693.jpg)
